version: "3"

services:
  db:
    image: postgres:10.1-alpine
    environment:
     - POSTGRES_USER=${DB_USERNAME}
     - POSTGRES_PASSWORD=${DB_PASSWORD}
     - POSTGRES_DB=${DB_NAME}
    volumes:
      - db-data:/var/lib/postgresql/data

  app:
    build: .
    environment:
      - FG_DB_HOST=db:5432
      - FG_DB_USERNAME=${DB_USERNAME}
      - FG_DB_PASSWORD=${DB_PASSWORD}
      - FG_DB_NAME=${DB_NAME}
    ports:
      - "80:80"
    depends_on:
      - db

volumes:
  db-data: